### ISSUE TITLE
Display for ready up

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#41]
A "Press [R] to ready up" at the top of the screen for the host will suffice.

**Comment by hermitec** [comment]
Contextual messages depending on status:

![image](https://user-images.githubusercontent.com/63280379/106379044-2ebdb080-63a1-11eb-8bdc-14c442d017b3.png)
POV: You're on a lobby on your own

![image](https://user-images.githubusercontent.com/63280379/106378999-ca025600-63a0-11eb-9421-1899e788dfcc.png)
POV: 2+ Players and you're the host

![image](https://user-images.githubusercontent.com/63280379/106378921-42b4e280-63a0-11eb-998e-6ab93ea448e2.png)
POV: 2+ Players and you aren't the host

I havent been able to test whether or not the message disappears properly because i'm euro but it should, will test later today probably then close after that

**Comment by hermitec** [comment]
![image](https://user-images.githubusercontent.com/63280379/106379104-9542ce80-63a1-11eb-962c-c47fbf558785.png)
position for context

**Comment by GlorifiedPig** [comment]
Cool, can you make the width of the text thing larger so that it always appears in 1 line

**Comment by hermitec** [comment]
> 
> 
> Cool, can you make the width of the text thing larger so that it always appears in 1 line

done probably

this is as good as it can get w/ current code, might come back to this some time later but this works just fine it just isnt as QOL as i'd like
