### ISSUE TITLE
Better Networking

### ISSUE THREAD

**Issue by kjeghueirgh** [GlorifiedStudios/Catch-Me-If-You-Can-Issues#61]
With the games current networking, there is no serverside verification on movement. There is 100% trust put into the client. This needs to be fixed so clients cant just teleport around, tag people from across the map, go outside the map, flyhack, etc.

As for the server user, they have complete control over the clients, and if they where to delete a player or set them as inactive, the players game will crash.

**Comment by kjeghueirgh** [comment]
https://streamable.com/jjr62a

**Comment by GlorifiedPig** [comment]
There's not too much we can do about server verification since the game is purely P2P and ran off Steamworks packets. There will be an anticheat to prevent memory modification & the CheatEngine speed hack, as well as a kick feature as the server host to kick cheaters or annoying players. There'll be a few ways to manually intervene if you host and a cheater joins, but as for anticheat methods can't do much without dedicated servers (else the hosts will just exploit the shit out of them anyways)

**Comment by GlorifiedPig** [comment]
Forgot to mention there'll also be variable obfuscation (with the seed networked) & it will be compiled with IL2CPP, so 90% of exploits should be stopped and people who are dedicated can just get kicked/banned from a lobby.
